require('dotenv').config();

module.exports = {
  PORT: process.env.PORT || 5000,
  NODE_ENV: process.env.NODE_ENV || 'development',
  MONGO_URI: process.env.MONGO_URI || 'mongodb://localhost:27017/myapp',
  FRONTEND_URL: process.env.FRONTEND_URL || 'http://localhost:3001',
  JWT_SECRET: process.env.JWT_SECRET || 'your-secret-key-should-be-long-and-complex',
  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN || '7d',  // String format
  SALT_ROUNDS: parseInt(process.env.SALT_ROUNDS) || 10,
  
  // Stripe (optional)
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
  STRIPE_BASIC_MONTHLY_PRICE_ID: process.env.STRIPE_BASIC_MONTHLY_PRICE_ID,
  STRIPE_BASIC_QUARTERLY_PRICE_ID: process.env.STRIPE_BASIC_QUARTERLY_PRICE_ID,
  STRIPE_BASIC_YEARLY_PRICE_ID: process.env.STRIPE_BASIC_YEARLY_PRICE_ID,
  STRIPE_PREMIUM_MONTHLY_PRICE_ID: process.env.STRIPE_PREMIUM_MONTHLY_PRICE_ID,
  STRIPE_PREMIUM_QUARTERLY_PRICE_ID: process.env.STRIPE_PREMIUM_QUARTERLY_PRICE_ID,
  STRIPE_PREMIUM_YEARLY_PRICE_ID: process.env.STRIPE_PREMIUM_YEARLY_PRICE_ID,
  STRIPE_ELITE_MONTHLY_PRICE_ID: process.env.STRIPE_ELITE_MONTHLY_PRICE_ID,
  STRIPE_ELITE_QUARTERLY_PRICE_ID: process.env.STRIPE_ELITE_QUARTERLY_PRICE_ID,
  STRIPE_ELITE_YEARLY_PRICE_ID: process.env.STRIPE_ELITE_YEARLY_PRICE_ID,
};